---
- name: Create 'sudodev' group for developers sudo
  group:
    name: sudodev
    state: present

- name: Add/remove developers accounts to server
  user:
    name: "{{ item.login }}"
    comment: "{{ item.name }}"
    groups: "{{ item.groups }}"
    state: "{{ item.state }}"
    shell: "{{ item.shell | default(user_shell) }}"
  with_items: "{{ developers }}"

- name: Add developers keys to server
  authorized_key:
    user: "{{ item.login }}"
    key: "https://{{ github_base_url }}/{{ item.github }}.keys"
    comment: "{{ item.name }}"
    exclusive: true
  with_items: "{{ developers }}"
  when: item.state == "present" and item.github is defined

- name: Add developers keys to server
  authorized_key:
    user: "{{ item.login }}"
    key: "{{ item.public_key }}"
    comment: "{{ item.name }}"
    exclusive: true
  with_items: "{{ developers }}"
  when: item.state == "present" and item.public_key is defined

- name: Allow 'sudodev' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudodev'
    line: '%sudodev ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
